### ISSUE TITLE
createMessage problem

### ISSUE THREAD

**Issue by arsewizz** [skygear-demo/ionic3-chat-demo#1]

**Comment by carmenlau** [comment]
@arsewizz Would you mind give more detail about the bug? Which platform you are using and how you trigger the bug?

**Comment by arsewizz** [comment]
just a quetion, with this example you have well defined your model. me in my application I search a user before sending a message

>    const query = new skygear.Query(skygear.UserRecord);
    query.equalTo('email', this.email);

and if there is the I can send a message. an idea related to your example?

**Comment by arsewizz** [comment]
I was able to solve the problem thank you
