### ISSUE TITLE
Support sending image

### ISSUE THREAD

**Issue by carmenlau** [skygear-demo/ionic3-chat-demo#5]
Format: https://github.com/SkygearIO/chat/blob/master/doc/message.md

FYI:
https://ionicframework.com/docs/native/image-resizer/
https://ionicframework.com/docs/native/image-picker/

**Comment by arsewizz** [comment]
can you use the camera? from where you can directly take a picture or choose one to send

**Comment by carmenlau** [comment]
@arsewizz In the current master we only support sending image from the image picker, so camera is not supported now
