### ISSUE TITLE
Support sending voice message

### ISSUE THREAD

**Issue by carmenlau** [skygear-demo/ionic3-chat-demo#6]
Format: https://github.com/SkygearIO/chat/blob/master/doc/message.md

- [ ] [Voice message] Record and send out voice message #15 
- [ ] [Voice message] Display voice message with play button #16

**Comment by arsewizz** [comment]
do you have any documentation on that? I can also work on it

**Comment by carmenlau** [comment]
@arsewizz We have planned to do the voice message demo now. If you are interested, maybe can help the image message demo add camera support? :)
